"""
Momentum Ranking Strategy - NO HINDSIGHT BIAS

Uses a point-in-time universe generated as of January 1, 2020.
All stocks in this universe:
1. Were publicly traded as of Jan 1, 2020
2. Had market cap > $5B
3. Had daily volume > $10M
4. Were well-known at that time (no obscure picks)

Excluded stocks that IPO'd after 2020:
- COIN, HOOD, UPST, AFRM, SOFI, ABNB, SNOW, DUOL, CAVA, TOST

This is the TRUE test of the momentum strategy without hindsight bias.
"""

from AlgorithmImports import *


class MomentumRankingNoHindsight(QCAlgorithm):

    def initialize(self):
        self.set_start_date(2020, 1, 1)
        self.set_end_date(2024, 12, 31)
        self.set_cash(100000)

        # Realistic trading constraints
        self.set_security_initializer(lambda security: security.set_slippage_model(
            ConstantSlippageModel(0.001)
        ))
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE)
        self.min_dollar_volume = 1_000_000

        # ============================================================
        # HINDSIGHT-FREE UNIVERSE (as of January 1, 2020)
        # ============================================================
        # Generated by: strategy-factory/universe/universe_generator.py
        # Selection criteria:
        #   - Market cap > $5B
        #   - Daily dollar volume > $10M
        #   - Beta > 1.0 vs SPY
        #   - Listed > 1 year (avoid recent IPOs)
        #   - Exclude: Utilities, REITs, Consumer Staples
        #
        # All 61 stocks were well-known and liquid as of Jan 2020.
        # NONE of the post-2020 IPO stocks are included.
        # ============================================================

        self.universe_tickers = [
            # Mega-cap tech (all established pre-2020)
            "AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "AMD", "INTC",
            "CRM", "ADBE", "NFLX",

            # Semiconductors (all established)
            "AVGO", "QCOM", "TXN", "MU", "AMAT", "LRCX", "KLAC", "MRVL",

            # Consumer discretionary (established)
            "TSLA", "NKE", "SBUX", "CMG", "LULU", "BKNG",

            # Travel/Leisure (cyclical, established)
            "RCL", "CCL", "MAR", "HLT", "WYNN", "LVS", "MGM",

            # Financials (established)
            "GS", "MS", "JPM", "SQ", "PYPL", "V", "MA",

            # Industrials (cyclical, established)
            "CAT", "DE", "BA", "HON", "URI",

            # Energy (volatile, established)
            "XOM", "CVX", "OXY", "SLB", "COP",

            # Growth tech (IPO'd 2016-2019, were known by 2020)
            "ROKU",  # IPO Sep 2017
            "TTD",   # IPO Sep 2016
            "CRWD",  # IPO Jun 2019
            "DDOG",  # IPO Sep 2019
            "NET",   # IPO Sep 2019
            "ZS",    # IPO Mar 2018
            "SNAP",  # IPO Mar 2017
            "PINS",  # IPO Apr 2019

            # Healthcare growth (established)
            "ISRG", "DXCM", "ALGN", "VEEV",
        ]

        # Strategy parameters
        self.lookback_days = 126  # 6 months
        self.top_n = 15
        self.use_regime_filter = True

        # SPY for regime filter
        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.spy_sma = self.sma(self.spy, 200, Resolution.DAILY)

        # Add universe
        self.symbols = []
        for ticker in self.universe_tickers:
            try:
                equity = self.add_equity(ticker, Resolution.DAILY)
                self.symbols.append(equity.symbol)
            except Exception as e:
                self.debug(f"Could not add {ticker}: {e}")

        # Momentum indicators
        self.momentum = {}
        self.volume_sma = {}
        for symbol in self.symbols:
            self.momentum[symbol] = self.roc(symbol, self.lookback_days, Resolution.DAILY)
            self.volume_sma[symbol] = self.sma(symbol, 20, Resolution.DAILY, Field.VOLUME)

        # Warmup
        self.set_warm_up(self.lookback_days + 10, Resolution.DAILY)

        # Monthly rebalance
        self.schedule.on(
            self.date_rules.month_start("SPY"),
            self.time_rules.after_market_open("SPY", 30),
            self.rebalance
        )

        self.set_benchmark("SPY")

    def rebalance(self):
        """Monthly rebalance with liquidity checks"""

        if self.is_warming_up:
            return

        # Regime filter
        if self.use_regime_filter:
            if not self.spy_sma.is_ready:
                return
            spy_price = self.securities[self.spy].price
            if spy_price < self.spy_sma.current.value:
                self.liquidate()
                self.debug(f"{self.time.date()}: Bear market - going to cash")
                return

        # Score symbols with liquidity check
        scores = {}
        for symbol in self.symbols:
            if symbol not in self.momentum:
                continue
            if not self.momentum[symbol].is_ready:
                continue
            if not self.securities[symbol].has_data:
                continue

            price = self.securities[symbol].price
            if price < 5:
                continue

            # Liquidity check
            if symbol in self.volume_sma and self.volume_sma[symbol].is_ready:
                avg_volume = self.volume_sma[symbol].current.value
                dollar_volume = avg_volume * price
                if dollar_volume < self.min_dollar_volume:
                    continue

            scores[symbol] = self.momentum[symbol].current.value

        if len(scores) < self.top_n:
            self.debug(f"{self.time.date()}: Not enough liquid stocks ({len(scores)})")
            return

        # Rank and select top N
        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        top_symbols = [s for s, _ in ranked[:self.top_n]]

        # Log selection
        top_picks_str = ", ".join([f"{s.value}:{scores[s]:.1f}%" for s in top_symbols[:5]])
        self.debug(f"{self.time.date()}: Top 5: {top_picks_str}")

        # Equal weight
        weight = 1.0 / self.top_n

        # Liquidate non-top positions
        for holding in self.portfolio.values():
            if holding.invested and holding.symbol not in top_symbols:
                self.liquidate(holding.symbol)

        # Rebalance
        for symbol in top_symbols:
            self.set_holdings(symbol, weight)

    def on_data(self, data):
        pass
