"""
Momentum Ranking Strategy - CLAUDE-GENERATED V3 (Quality Momentum)

Balanced universe: High-beta but quality (profitable, US-focused, market leaders)
No Chinese ADRs, no legacy tech, no speculative unprofitable.

Generated by: strategy-factory/universe/claude_universe_generator.py
"""

from AlgorithmImports import *


class MomentumRankingClaudeV3(QCAlgorithm):

    def initialize(self):
        self.set_start_date(2020, 1, 1)
        self.set_end_date(2024, 12, 31)
        self.set_cash(100000)

        self.set_security_initializer(lambda security: security.set_slippage_model(
            ConstantSlippageModel(0.001)
        ))
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE)
        self.min_dollar_volume = 1_000_000

        # ============================================================
        # CLAUDE-GENERATED V3: Quality Momentum (56 stocks)
        # ============================================================
        # High-beta + Quality: Profitable, US-focused, market leaders
        # No Chinese ADRs, no legacy tech, no speculative
        # ============================================================

        self.universe_tickers = [
            # Semiconductors (10) - cyclical, high beta
            "NVDA", "AMD", "AVGO", "QCOM", "MU", "AMAT", "LRCX", "KLAC", "MRVL", "ON",
            "TXN", "ADI", "SNPS", "CDNS", "ASML",

            # Software leaders (10) - proven, profitable
            "CRM", "ADBE", "NOW", "INTU", "PANW", "VEEV", "WDAY",

            # Payments/Fintech (4)
            "V", "MA", "PYPL", "SQ",

            # E-commerce (2)
            "AMZN", "SHOP",

            # Travel/Leisure (6) - cyclical, high beta
            "BKNG", "RCL", "CCL", "MAR", "HLT", "WYNN",

            # Energy (6) - volatile, cyclical
            "XOM", "CVX", "OXY", "DVN", "SLB", "COP",

            # Industrials (4) - cyclical leaders
            "CAT", "DE", "URI", "BA",

            # Consumer growth (5) - brand leaders
            "TSLA", "NKE", "LULU", "CMG", "DECK",

            # Investment banks (2)
            "GS", "MS",

            # Streaming (2)
            "NFLX", "ROKU",
        ]

        self.lookback_days = 126
        self.top_n = 15
        self.use_regime_filter = True

        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.spy_sma = self.sma(self.spy, 200, Resolution.DAILY)

        self.symbols = []
        for ticker in self.universe_tickers:
            try:
                equity = self.add_equity(ticker, Resolution.DAILY)
                self.symbols.append(equity.symbol)
            except Exception as e:
                self.debug(f"Could not add {ticker}: {e}")

        self.momentum = {}
        self.volume_sma = {}
        for symbol in self.symbols:
            self.momentum[symbol] = self.roc(symbol, self.lookback_days, Resolution.DAILY)
            self.volume_sma[symbol] = self.sma(symbol, 20, Resolution.DAILY, Field.VOLUME)

        self.set_warm_up(self.lookback_days + 10, Resolution.DAILY)

        self.schedule.on(
            self.date_rules.month_start("SPY"),
            self.time_rules.after_market_open("SPY", 30),
            self.rebalance
        )

        self.set_benchmark("SPY")

    def rebalance(self):
        if self.is_warming_up:
            return

        if self.use_regime_filter:
            if not self.spy_sma.is_ready:
                return
            spy_price = self.securities[self.spy].price
            if spy_price < self.spy_sma.current.value:
                self.liquidate()
                self.debug(f"{self.time.date()}: Bear market - going to cash")
                return

        scores = {}
        for symbol in self.symbols:
            if symbol not in self.momentum:
                continue
            if not self.momentum[symbol].is_ready:
                continue
            if not self.securities[symbol].has_data:
                continue

            price = self.securities[symbol].price
            if price < 5:
                continue

            if symbol in self.volume_sma and self.volume_sma[symbol].is_ready:
                avg_volume = self.volume_sma[symbol].current.value
                dollar_volume = avg_volume * price
                if dollar_volume < self.min_dollar_volume:
                    continue

            scores[symbol] = self.momentum[symbol].current.value

        if len(scores) < self.top_n:
            return

        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        top_symbols = [s for s, _ in ranked[:self.top_n]]

        top_picks_str = ", ".join([f"{s.value}:{scores[s]:.1f}%" for s in top_symbols[:5]])
        self.debug(f"{self.time.date()}: Top 5: {top_picks_str}")

        weight = 1.0 / self.top_n

        for holding in self.portfolio.values():
            if holding.invested and holding.symbol not in top_symbols:
                self.liquidate(holding.symbol)

        for symbol in top_symbols:
            self.set_holdings(symbol, weight)

    def on_data(self, data):
        pass
